### ISSUE TITLE
General question on mobius design

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/mobius#47]
From what I can see, it seems like mobius is doing something similar to flink and spark, saving states in two level storages(local & remote).

Yet, there is a paper Hazelcast https://arxiv.org/abs/2103.10169 In there design, they directly use in-memory storage to handle states distributedly. If mobius can use the fundamental ray core object store to do something similar, will it be much faster?

**Comment by ashione** [comment]
> From what I can see, it seems like mobius is doing something similar to flink and spark, saving states in two level storages(local & remote).
> 
> Yet, there is a paper Hazelcast https://arxiv.org/abs/2103.10169 In there design, they directly use in-memory storage to handle states distributedly. If mobius can use the fundamental ray core object store to do something similar, will it be much faster?

It sounds good suggestion. In current design, it contains two level phases for storing state data, but we can make a job 
reconstruction within tiny scope actors and works by buffering a part of transported data in upstreams(https://docs.google.com/document/d/1NKjGr7fi-45cEzWA-N_wJ5CoUgaJfnsW9YeWsSg1shY). BTW, our contributor @clay4444 has do some researches on Hazelcast.

**Comment by clay4444** [comment]
> 

Hi, @wilsonwang371 , I made some research about Hazelcast before, I think we can separate this question into two sub-questions.
1. About the part of the performance, the advantage of `Hazelcast` is its processing model, it includes the `Cooperative Thread`, `Event loop`, and a separated thread that handles the JVM GC to improve the performance. Actually, the IMDG can not bring performance improvement.
2. About the data consist model which is very confusing to me before, The IMDG can cover some FO cases, such as we have three replicas of the data and one or two nodes down, however, the data will be lost forever if these three nodes all down, which is not acceptable for us.

**Comment by clay4444** [comment]
> From what I can see, it seems like mobius is doing something similar to flink and spark, saving states in two level storages(local & remote).
> 
> Yet, there is a paper Hazelcast https://arxiv.org/abs/2103.10169 In there design, they directly use in-memory storage to handle states distributedly. If mobius can use the fundamental ray core object store to do something similar, will it be much faster?

Hi, @wilsonwang371 , I made some research about Hazelcast before, I think we can separate this question into two sub-questions.
1. About the part of the performance, the advantage of Hazelcast is its processing model, it includes the Cooperative Thread, Event loop, and a separated thread that handles the JVM GC to improve the performance. Actually, the IMDG can not bring performance improvement.
2. About the data consist model which is very confusing to me before, The IMDG can cover some FO cases, such as we have three replicas of the data and one or two nodes down, however, the data will be lost forever if these three nodes all down, which is not acceptable for us.

**Comment by ashione** [comment]
@wilsonwang371 Our design tests in antgroup internal version within P99 10ms latency between one upstream and one downstream edges as well. Actually memory state store is not key point for making low latency processing if async state io supported.

**Comment by wilsonwang371** [comment]
Thanks for the reply, yeah @clay4444 you are right, lightweight coroutine, reduced GC, dedicated i/o threads are some of the main contributions in Hazelcast paper. besides, they also mentioned that multiple transforms can be scheduled on the same node so that their data can be shared inside the memory to improve the performance.

I am just thinking the major difference other than the things mentioned above. Will there be some significant difference that can affect the performance? 

To me, when comparing IMDG and ray, the differences are: 
1. Objects in IMDG seem to be mutable while in Ray, it is immutable. 
2. How is this implemented in Ray streaming? I suppose data between stages are similar to what flink does and it uses local and remote ray kv to save the data. Compared with Hazelcast, it does not use the *local storage* used in ray streaming. Will this provide significant performance improvement for ray streaming compared with Hazelcast?
3. If lightweight coroutine can give performance improvement, why don't we consider it in Ray streaming? Also, as GC can affect the latency, did we ever consider using C++ instead of Java while doing Mobius implementation?

cc @ashione 


Thanks

**Comment by ashione** [comment]
> Thanks for the reply, yeah @clay4444 you are right, lightweight coroutines, reduced GC, and dedicated i/o threads are some of the main contributions to Hazelcast paper. besides, they also mentioned that multiple transforms can be scheduled on the same node so that their data can be shared inside the memory to improve the performance.
> 
> I am just thinking about the major difference other than the things mentioned above. Will there be some significant difference that can affect the performance?
> 
> To me, when comparing IMDG and ray, the differences are:
> 
> 1. Objects in IMDG seem to be mutable while in Ray, it is immutable.
> 2. How is this implemented in Ray streaming? I suppose data between stages are similar to what flink does and it uses local and remote ray KV storage to save the data. Compared with Hazelcast, it does not use the _local storage_ used in ray streaming. Will this provide significant performance improvement for ray streaming compared with Hazelcast?
> 3. If lightweight coroutine can give performance improvement, why don't we consider it in Ray streaming? Also, as GC can affect the latency, did we ever consider using C++ instead of Java while doing Mobius implementation?
> 
> cc @ashione
> 
> Thanks

We wanna to provide some natives usage from initial design beginning. And based on that, it is whole native stack implementation coded by cpp. But the technical architecture of the implementation is selected according to user needs(etc. Many devs use python on AI infra). 
It's said that we provided java and python operator/function since we truly use that in our production. Actually, pure c++ function/api will be comming soon.

For state-wise, it's another big picture for us. There are other storage teams in antgroup company who can serve us a much more fast kv database, we hope these software could be used in open source community.
