### ISSUE TITLE
[bug] InputStreamTask.run   

### ISSUE THREAD

**Issue by lpydhbt** [ray-project/mobius#5]
1. ray version:1.9.1
2. java version:Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
3. env:mac os 12.1 
4. "KeyByFucntion generic type"：HashMap<String,String>

- BUG1:on run-mode = SINGLE_PROCESS,when I use dataStream function "keyBy",then transfrom data in other woker node,i found in big data,may hava 2 errors occur。
- BUG2:on run-mode = CLUSTER.when I use dataStream function "keyBy",then transfrom data in another woker node,another woker node jvm crashed。

- BUG1：may 1st error:
```
2022-01-19 17:55:30,268 INFO JobMaster [pool-3-thread-1]: Vertex ExecutionVertex{id=1, name=4-[FlatMapOperator -> OpenSinkOperator]-0, resources={}, state=TO_ADD, containerId=ContainerId{id=b6b0fdaa-1b56-4343-b754-2cb53d7747ee}, workerActor=io.ray.runtime.actor.LocalModeActorHandle@67341926} request rollback, exception msg : java.lang.ClassCastException: java.lang.Byte cannot be cast to java.util.List
	at io.ray.streaming.runtime.serialization.CrossLangSerializer.deserialize(CrossLangSerializer.java:38)
	at io.ray.streaming.runtime.serialization.CrossLangSerializer.deserialize(CrossLangSerializer.java:12)
	at io.ray.streaming.runtime.worker.tasks.InputStreamTask.run(InputStreamTask.java:64)
	at io.ray.runtime.AbstractRayRuntime.lambda$wrapRunnable$2(AbstractRayRuntime.java:246)
	at java.lang.Thread.run(Thread.java:748)
 ```

- BUG1:may 2nd error:
```
2022-01-19 18:09:03,354 ERROR InputStreamTask [io.ray.streaming.runtime.worker.tasks.OneInputStreamTask-1642586922675]: Last success checkpointId=0, now occur error.
java.lang.IllegalArgumentException: null
	at java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_231]
	at io.ray.streaming.runtime.transfer.DataReader.getDataMessage(DataReader.java:180) ~[streaming-runtime-1.9.2.jar:?]
	at io.ray.streaming.runtime.transfer.DataReader.read(DataReader.java:134) ~[streaming-runtime-1.9.2.jar:?]
	at io.ray.streaming.runtime.worker.tasks.InputStreamTask.run(InputStreamTask.java:47) ~[streaming-runtime-1.9.2.jar:?]
	at io.ray.runtime.AbstractRayRuntime.lambda$wrapRunnable$2(AbstractRayRuntime.java:246) ~[ray-runtime-1.9.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
 ```
- BUG2:
 ```
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  SIGSEGV (0xb) at pc=0x0000000124c25a03, pid=52940, tid=0x0000000000009f03
  #
  # JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
  # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode bsd-amd64 compressed oops)
  # Problematic frame:
  # C  [libstreaming_java.dylib+0x37a03]  _ZN3ray9streaming12MockConsumer21NotifyChannelConsumedEy+0x53
  #
  # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  #
  # If you would like to submit a bug report, please visit:
  #   http://bugreport.java.com/bugreport/crash.jsp
  # The crash happened outside the Java Virtual Machine in native code.
  # See problematic frame for where to report the bug.
  
  Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
  C  [libstreaming_java.dylib+0x37a03]  _ZN3ray9streaming12MockConsumer21NotifyChannelConsumedEy+0x53
  C  [libstreaming_java.dylib+0x10ac9]  _ZN3ray9streaming10DataReader18NotifyConsumedItemERNS0_19ConsumerChannelInfoEy+0x1b9
  C  [libstreaming_java.dylib+0x23278]  _ZN3ray9streaming17ReliabilityHelper17HandleNoValidItemERNS0_19ConsumerChannelInfoE+0x1a8
  C  [libstreaming_java.dylib+0xd9e0]  _ZN3ray9streaming10DataReader21GetMessageFromChannelERNS0_19ConsumerChannelInfoERNSt3__110shared_ptrINS0_10DataBundleEEEjj+0x6f0
  C  [libstreaming_java.dylib+0xc402]  _ZN3ray9streaming10DataReader17InitChannelMergerEj+0x392
  C  [libstreaming_java.dylib+0xfdac]  _ZN3ray9streaming10DataReader9GetBundleEjRNSt3__110shared_ptrINS0_10DataBundleEEE+0x25c
  C  [libstreaming_java.dylib+0x26be]  Java_io_ray_streaming_runtime_transfer_DataReader_getBundleNative+0x2e
  j  io.ray.streaming.runtime.transfer.DataReader.getBundleNative(JJJJ)V+0
  j  io.ray.streaming.runtime.transfer.DataReader.getBundle(J)V+20
  j  io.ray.streaming.runtime.transfer.DataReader.read(J)Lio/ray/streaming/runtime/transfer/message/ChannelMessage;+14
  j  io.ray.streaming.runtime.worker.tasks.InputStreamTask.run()V+25
  j  io.ray.runtime.AbstractRayRuntime.lambda$wrapRunnable$2(Ljava/lang/Object;Ljava/lang/Runnable;)V+11
  j  io.ray.runtime.AbstractRayRuntime$$Lambda$65.run()V+12
  j  java.lang.Thread.run()V+11
  v  ~StubRoutines::call_stub
  V  [libjvm.dylib+0x2f0792]
  V  [libjvm.dylib+0x2f0f36]
  V  [libjvm.dylib+0x2f10e2]
  V  [libjvm.dylib+0x34b9d1]
  V  [libjvm.dylib+0x571817]
  V  [libjvm.dylib+0x572f12]
  V  [libjvm.dylib+0x48f0fa]
  C  [libsystem_pthread.dylib+0x64f4]  _pthread_start+0x7d
  C  [libsystem_pthread.dylib+0x200f]  thread_start+0xf
  C  0x0000000000000000
  
  Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
  j  io.ray.streaming.runtime.transfer.DataReader.getBundleNative(JJJJ)V+0
  j  io.ray.streaming.runtime.transfer.DataReader.getBundle(J)V+20
  j  io.ray.streaming.runtime.transfer.DataReader.read(J)Lio/ray/streaming/runtime/transfer/message/ChannelMessage;+14
  j  io.ray.streaming.runtime.worker.tasks.InputStreamTask.run()V+25
  j  io.ray.runtime.AbstractRayRuntime.lambda$wrapRunnable$2(Ljava/lang/Object;Ljava/lang/Runnable;)V+11
  j  io.ray.runtime.AbstractRayRuntime$$Lambda$65.run()V+12
  j  java.lang.Thread.run()V+11
  v  ~StubRoutines::call_stub
 ```

**Comment by ashione** [comment]
Could u provide simplified code for us? I will try to reproduce your methioned above exception.

**Comment by lpydhbt** [comment]
[](url
[raystreamTest.zip](https://github.com/ray-project/mobius/files/7896416/raystreamTest.zip)
)
test class: com.ray.TestGateAwayStream

**Comment by ashione** [comment]
> [](url [raystreamTest.zip](https://github.com/ray-project/mobius/files/7896416/raystreamTest.zip) ) test class: com.ray.TestGateAwayStream

@lpydhbt 
Thanks for providing this source codes.
It works on my laptop when I remove line25 of `TestGateAwayStream.java`.


Hints:
Memory channel transporting is only for single process mode.( one process can not fetch native memory from other process in mock memory channel, so you get this exception).
You might turn on native channel on cluster model.

**Comment by lpydhbt** [comment]
@ashione 
sry,there hava 2 questions,
first,i`m use Memory channel and  single process mode(use ray.conf) ,replicate occuer exception(i have methioned BUG1 on head comment：CrossLangSerializer.deserialize or  java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_231])

2nd:change ray.conf  (run-mode = CLUSTER) and use  NATIVE_CHANNEL。i found another question：In FileSourceFunction produce size is Integer.MAX_VALUE。but only source produce 72090 data。In log file raylet.err :I found  this error "[2022-01-19 20:52:17,909 E 58605 6507608] data_reader.cc:88: Initialize queue failed, id=0000000000000000726504e000000000000000010000000000000000, status=0"

by the way :👍

**Comment by ashione** [comment]
> 

Paste all of output context or log files might help us to find rootcause. (including raylet.out/err and java_core_worker.log/err)

For filesize case, test case produces tiny output file on my machine.

**Comment by lpydhbt** [comment]
> Paste all of output context or log files might help us to find rootcause. (including raylet.out/err and java_core_worker.log/err)
> 
> For filesize case, test case produces tiny output file on my machine.
> 
> > @ashione sry,there also hava 2 questions, first,i`m use Memory channel and single process mode(use ray.conf) ,replicate occuer exception(i have methioned BUG1 on head comment：CrossLangSerializer.deserialize or java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_231])
> > 2nd:change ray.conf (run-mode = CLUSTER) and use NATIVE_CHANNEL。i found another question：In FileSourceFunction produce size is Integer.MAX_VALUE。but only source produce 72090 data。In log file raylet.err :I found this error "[2022-01-19 20:52:17,909 E 58605 6507608] data_reader.cc:88: Initialize queue failed, id=0000000000000000726504e000000000000000010000000000000000, status=0"
> > by the way :👍

log:
- sink operator log:
[java-worker-2d000000-73262.log](https://github.com/ray-project/mobius/files/7901752/java-worker-2d000000-73262.log)

- source operaor log:

- raylet log:
[raylet.err.log](https://github.com/ray-project/mobius/files/7901759/raylet.err.log)

- sink code:
```
package com.ray;

import com.alibaba.fastjson.JSON;
import io.ray.streaming.api.context.RuntimeContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;

/**
 * fileSinkFunction
 *
 * @date 2022-01-18
 **/
public class FileSinkFunction implements OpenSinkFunction<HashMap<String,String>>{

    private static final Logger LOG = LoggerFactory.getLogger(FileSinkFunction.class);
    String fileName;
    Object fileObj;

    public FileSinkFunction(String fileName) {
        this.fileName = fileName;
    }
    int i = 0;
    @Override
    public void sink(HashMap<String, String> value) {
        LOG.info("sink"+i++);
        try {
            ((BufferedWriter)fileObj).write(i++ +"\n");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void open(RuntimeContext runtimeContext) {
        try {
            File file = new File(fileName);
            if(!file.exists()) {
                file.createNewFile();

            }
            BufferedWriter out = new BufferedWriter(new FileWriter(fileName));
            fileObj = out;
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}

```

**Comment by ashione** [comment]
> > Paste all of output context or log files might help us to find rootcause. (including raylet.out/err and java_core_worker.log/err)
> > For filesize case, test case produces tiny output file on my machine.
> > > @ashione sry,there also hava 2 questions, first,i`m use Memory channel and single process mode(use ray.conf) ,replicate occuer exception(i have methioned BUG1 on head comment：CrossLangSerializer.deserialize or java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_231])
> > > 2nd:change ray.conf (run-mode = CLUSTER) and use NATIVE_CHANNEL。i found another question：In FileSourceFunction produce size is Integer.MAX_VALUE。but only source produce 72090 data。In log file raylet.err :I found this error "[2022-01-19 20:52:17,909 E 58605 6507608] data_reader.cc:88: Initialize queue failed, id=0000000000000000726504e000000000000000010000000000000000, status=0"
> > > by the way :👍
> 
> * one question:MODE=CLUSTER && CHANNEL_TYPE= NATIVE_CHANNEL
>   
>   * sink operator log:
> 
> [java-worker-2d000000-73262.log](https://github.com/ray-project/mobius/files/7901752/java-worker-2d000000-73262.log)
> 
> ```
> - raylet log:
> ```
> 
> [raylet.err.log](https://github.com/ray-project/mobius/files/7901759/raylet.err.log)
> 
> ```
> - sink code:
> ```
> 
> ```
> package com.ray;
> 
> import com.alibaba.fastjson.JSON;
> import io.ray.streaming.api.context.RuntimeContext;
> import org.slf4j.Logger;
> import org.slf4j.LoggerFactory;
> 
> import java.io.BufferedWriter;
> import java.io.File;
> import java.io.FileWriter;
> import java.io.IOException;
> import java.util.HashMap;
> 
> /**
>  * fileSinkFunction
>  *
>  * @date 2022-01-18
>  **/
> public class FileSinkFunction implements OpenSinkFunction<HashMap<String,String>>{
> 
>     private static final Logger LOG = LoggerFactory.getLogger(FileSinkFunction.class);
>     String fileName;
>     Object fileObj;
> 
>     public FileSinkFunction(String fileName) {
>         this.fileName = fileName;
>     }
>     int i = 0;
>     @Override
>     public void sink(HashMap<String, String> value) {
>         LOG.info("sink"+i++);
>         try {
>             ((BufferedWriter)fileObj).write(i++ +"\n");
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>     }
> 
>     @Override
>     public void open(RuntimeContext runtimeContext) {
>         try {
>             File file = new File(fileName);
>             if(!file.exists()) {
>                 file.createNewFile();
> 
>             }
>             BufferedWriter out = new BufferedWriter(new FileWriter(fileName));
>             fileObj = out;
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>     }
> 
> }
> ```
> 
> * antoher question:MODE=SINGLE_PROCESS && CHANNEL_TYPE=MEMORY_CHANNEL
>   log:
>   [single_process.log](https://github.com/ray-project/mobius/files/7901848/single_process.log)

According to raylet.err log outputs, It's not error actually. 
`Initialize queue failed,` does not mean that's exception(it happends if and only if downstream had been started before upstream). I'll change this loglevel to warning, which would make less confusion.

**Comment by lpydhbt** [comment]
> In FileSourceFunction produce size is Integer.MAX_VALUE。but only source produce 72090 data。In log fi

**Comment by lpydhbt** [comment]
@ashione 
if raylet.err is not error,but my laptop also have 2 methioned questions。CLUSETER MODE sourceFunction process data length less  than  Intger.MaxValue and SINGLE_PROCESS deserialize use CrossLangSerializer(may occur)

**Comment by ashione** [comment]
> 

I guess this file is opened and unclosed in the end. What's your env? Linux or Mac OS

**Comment by ashione** [comment]
> @ashione if raylet.err is not error,but my laptop also have 2 methioned questions。CLUSETER MODE sourceFunction process data length less than Intger.MaxValue(sourceFunction process for Inger.MaxValue) and SINGLE_PROCESS deserialize use CrossLangSerializer(may occur)

**Comment by lpydhbt** [comment]
> I guess this file is opened and unclosed in the end. What's your env? Linux or Mac OS

not because of File sink or produce,i just use SourceFunction produce data by itatator Integer.MAX_VALUE, then -> keyBy  and then -> sink。SinkFunction  sink data only use LOGGER.info().the error also duplicate occur。

**Comment by ashione** [comment]
> > I guess this file is opened and unclosed in the end. What's your env? Linux or Mac OS
> 
> @ashione env:mac os 12.1； not because of File sink or produce,i just use SourceFunction produce data by itatator Integer.MAX_VALUE, then -> keyBy and then -> sink。SinkFunction sink data only use LOGGER.info().the error also duplicate occur。The proceedings were suspended in mid-stream。 and if I remove keyBy,these error not happen. [raystreamTest.zip](https://github.com/ray-project/mobius/files/7902660/raystreamTest.zip)

Got it. It's longrunning job matter. It's unsupported for keeping longg running if driver process exit in Ray OSS .
This issue can helpful for u. https://github.com/ray-project/ray/issues/6715

**Comment by ashione** [comment]
Driver will exit after 300 seconds running.

**Comment by lpydhbt** [comment]
> Driver will exit after 300 seconds running.

but in my laptop,use Thread.sleep(Integer.MAX_VALUE) for process not Exit,but driver exit。and if i remove KeyByFunction ,why  longrunning job  is useful。

**Comment by ashione** [comment]
> > Driver will exit after 300 seconds running.
> > @ashione
> > but in my laptop,use Thread.sleep(Integer.MAX_VALUE) for keeping driver process running,but driver exit。and if i remove KeyByFunction ,why longrunning job  work well。

There will be only one execution vertex after graph optimized, which means both source operator and sink operator are in one single process, so you can get result without any IPC.

The job has been created with two execution vertices if keyby function used since keyby could not be chained in one vertex.

**Comment by lpydhbt** [comment]
> in one single process, so you can get result without any IPC.

" in one single process" also create  master Actor  and then  this master Actor create JobWoker actor  and submit oprator task。 "in one single process"  is  also a long runnig job。

**Comment by ashione** [comment]
> > in one single process, so you can get result without any IPC.
> 
> " in one single process" also create master Actor and then this master Actor create JobWoker actor and submit oprator task。 "in one single process" is also a long runnig job。

How many nodes has been used in your cluster? Could you upload this ray-session-logs? Specificed directory is `/tmp/ray/session-xxx` by default.

**Comment by lpydhbt** [comment]
only one master node.
ports_by_node.json:
{"10.254.165.206:/tmp/ray/session_2022-01-20_13-53-56_185735_77613/sockets/plasma_store": {"metrics_agent_port": 64051, "metrics_export_port": 57163}}

**Comment by ashione** [comment]
> only one master node. ports_by_node.json: {"10.254.165.206:/tmp/ray/session_2022-01-20_13-53-56_185735_77613/sockets/plasma_store": {"metrics_agent_port": 64051, "metrics_export_port": 57163}} [session_latest.zip](https://github.com/ray-project/mobius/files/7903252/session_latest.zip)

Uploaded zip is symbol file with only 40+bytes.

**Comment by lpydhbt** [comment]
> > only one master node. ports_by_node.json: {"10.254.165.206:/tmp/ray/session_2022-01-20_13-53-56_185735_77613/sockets/plasma_store": {"metrics_agent_port": 64051, "metrics_export_port": 57163}} [session_latest.zip](https://github.com/ray-project/mobius/files/7903252/session_latest.zip)
> 
> Uploaded zip is symbol file with only 40+bytes.

update upload

**Comment by lpydhbt** [comment]
by the way,i use  Thread.sleep(Integer.MAX_VALUE) for driver keep。and ray-dashboard show  javaWoker is alive。

**Comment by ashione** [comment]
> by the way,i use Thread.sleep(Integer.MAX_VALUE) for driver keep。and ray-dashboard show javaWoker is alive。

I'll traige this issue in my local machine. Let u know if any updates ASAP.

**Comment by ashione** [comment]
@lpydhbt I fix this issue in PR https://github.com/ray-project/mobius/pull/10. You might try to use in source code deps or waiting next version release.

**Comment by lpydhbt** [comment]
in PR #10, exception is also exist.Maybe it was just modified MockProducer but use CLUSTER.

**Comment by ashione** [comment]
> 

Cluster deploy jar/so should be updated in new version. Otherwise, the old jar/library might be loaded in runtime.

**Comment by lpydhbt** [comment]
build code on my laptop,jar/so is replaced。and i use RUN_MODE = SINGLE_PROCESS or CLUSTER。the quesion is still  exit.

**Comment by ashione** [comment]
> build code on my laptop,jar/so is replaced。and i use RUN_MODE = SINGLE_PROCESS or CLUSTER。the quesion is still exit.

Nope. Jar will be loaded in runtime from ray wheel package jars directory, which makes a all in one fat-jar named ray-dist.jar.

**Comment by lpydhbt** [comment]
install ray-dist.jar the exception in CLUSTER is disappeared。but in SINGLE_PROCESS  the exception of "CrossLangSerializer.deserialize"(head of comment) is  also exit.

**Comment by ashione** [comment]
> install ray-dist.jar the exception in CLUSTER is disappeared。but in SINGLE_PROCESS the exception of "CrossLangSerializer.deserialize"(head of comment) is also exit.

- Build ray in master branch, install java package and restart ray cluster
- Build streaming in master branch, install java snapshot snapshot.
- Change your pom.xml to 2.0.0-SNAPSHOT

**Comment by ashione** [comment]
It works well on my laptop after I do these steps above mentioned.  
![image](https://user-images.githubusercontent.com/7359537/150758687-26458d9c-30bd-41a3-8d58-b4217879f98e.png)

**Comment by ashione** [comment]
@lpydhbt any updates about that?

**Comment by lpydhbt** [comment]
> @lpydhbt any updates about that?

we built the snapshot version from master branch.

1. for native channel running: it works

2. for memory channel running:  the jobworker always got an error when running your test job, seems that the job worker die due to an unexpect byte, and then framwork will try to recover the jobworker again and again. some detail logs as below:

2022-01-26 16:36:49,763 INFO JobClientImpl [TestNG-method=testUserDefinedSourceWordCount-1]: Finish submitting job: testUserDefinedSourceWordCount.
2022-01-26 16:36:49,764 INFO WordCountTest [TestNG-method=testUserDefinedSourceWordCount-1]: Total word size : 0.
2022-01-26 16:36:50,487 ERROR InputStreamTask [io.ray.streaming.runtime.worker.tasks.OneInputStreamTask-1643186209487]: Last success checkpointId=0, now occur error.
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.util.List
	at io.ray.streaming.runtime.serialization.CrossLangSerializer.deserialize(CrossLangSerializer.java:38) ~[streaming-runtime-2.0.0-SNAPSHOT.jar:?]
	at io.ray.streaming.runtime.serialization.CrossLangSerializer.deserialize(CrossLangSerializer.java:12) ~[streaming-runtime-2.0.0-SNAPSHOT.jar:?]
	at io.ray.streaming.runtime.worker.tasks.InputStreamTask.run(InputStreamTask.java:64) ~[streaming-runtime-2.0.0-SNAPSHOT.jar:?]
	at io.ray.runtime.AbstractRayRuntime.lambda$wrapRunnable$2(AbstractRayRuntime.java:256) ~[ray-runtime-2.0.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
2022-01-26 16:36:50,500 INFO JobWorker [io.ray.streaming.runtime.worker.tasks.OneInputStreamTask-1643186209487]: Request rollback.
2022-01-26 16:36:50,524 INFO JobMaster [pool-3-thread-1]: Vertex ExecutionVertex{id=1, name=4-[ReduceOperator -> SinkOperator]-0, resources={}, state=TO_ADD, containerId=ContainerId{id=f453da9a-b0a2-4366-8287-9d2ae5052f34}, workerActor=io.ray.runtime.actor.LocalModeActorHandle@6c0fd75d}, request job worker rollback cost 3ms, actorId=378c5378208707074fa846477c398dae.
2022-01-26 16:36:50,525 INFO ResourceManagerImpl [pool-3-thread-1]: Current resource detail: Resources{registerContainers=[Container{id=ContainerId{id=cb86bc41-5a48-4302-b1a3-c2d74be243a9}, address=localhost1, hostname=localhost1, nodeId=31313131313131313131313131313131313131313131313131313131, availableResources={MEM=16.0, ContainerId{id=cb86bc41-5a48-4302-b1a3-c2d74be243a9}=500.0, CPU=1.0}, executionVertexIds=[0], capacity=1}, Container{id=ContainerId{id=f453da9a-b0a2-4366-8287-9d2ae5052f34}, address=localhost2, hostname=localhost2, nodeId=32323232323232323232323232323232323232323232323232323232, availableResources={MEM=16.0, ContainerId{id=f453da9a-b0a2-4366-8287-9d2ae5052f34}=500.0, CPU=2.0}, executionVertexIds=[1], capacity=1}, Container{id=ContainerId{id=b65ea6ba-331e-46e1-b5d6-3f6e4ef5f417}, address=localhost3, hostname=localhost3, nodeId=33333333333333333333333333333333333333333333333333333333, availableResources={MEM=16.0, ContainerId{id=b65ea6ba-331e-46e1-b5d6-3f6e4ef5f417}=500.0, CPU=3.0}, executionVertexIds=[], capacity=1}, Container{id=ContainerId{id=dd6ab2d6-2d02-437e-8d26-6a45f5946d3b}, address=localhost4, hostname=localhost4, nodeId=34343434343434343434343434343434343434343434343434343434, availableResources={MEM=16.0, CPU=4.0, ContainerId{id=dd6ab2d6-2d02-437e-8d26-6a45f5946d3b}=500.0}, executionVertexIds=[], capacity=1}, Container{id=ContainerId{id=0fb276b8-edd3-46b6-a270-618bc0be3994}, address=localhost5, hostname=localhost5, nodeId=35353535353535353535353535353535353535353535353535353535, availableResources={MEM=16.0, ContainerId{id=0fb276b8-edd3-46b6-a270-618bc0be3994}=500.0, CPU=5.0}, executionVertexIds=[], capacity=1}]}.
2022-01-26 16:36:50,527 INFO FailoverCoordinator [pool-3-thread-1]: Request job worker rollback

**Comment by ashione** [comment]
> > @lpydhbt any updates about that?
> 
> 
> 
> we built the snapshot version from master branch and remove Ray.init().
> 
> 
> 
> 1. for native channel running: it works
> 
> 
> 
> 2. for memory channel running:  the jobworker always got an error when running your test job, seems that the job worker die due to an unexpect byte, and then framwork will try to recover the jobworker again and again. some detail logs as below:
> 
> 
> 
> 2022-01-26 16:36:49,763 INFO JobClientImpl [TestNG-method=testUserDefinedSourceWordCount-1]: Finish submitting job: testUserDefinedSourceWordCount.
> 
> 2022-01-26 16:36:49,764 INFO WordCountTest [TestNG-method=testUserDefinedSourceWordCount-1]: Total word size : 0.
> 
> 2022-01-26 16:36:50,487 ERROR InputStreamTask [io.ray.streaming.runtime.worker.tasks.OneInputStreamTask-1643186209487]: Last success checkpointId=0, now occur error.
> 
> java.lang.ClassCastException: java.lang.Byte cannot be cast to java.util.List
> 
> 	at io.ray.streaming.runtime.serialization.CrossLangSerializer.deserialize(CrossLangSerializer.java:38) ~[streaming-runtime-2.0.0-SNAPSHOT.jar:?]
> 
> 	at io.ray.streaming.runtime.serialization.CrossLangSerializer.deserialize(CrossLangSerializer.java:12) ~[streaming-runtime-2.0.0-SNAPSHOT.jar:?]
> 
> 	at io.ray.streaming.runtime.worker.tasks.InputStreamTask.run(InputStreamTask.java:64) ~[streaming-runtime-2.0.0-SNAPSHOT.jar:?]
> 
> 	at io.ray.runtime.AbstractRayRuntime.lambda$wrapRunnable$2(AbstractRayRuntime.java:256) ~[ray-runtime-2.0.0-SNAPSHOT.jar:?]
> 
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
> 
> 2022-01-26 16:36:50,500 INFO JobWorker [io.ray.streaming.runtime.worker.tasks.OneInputStreamTask-1643186209487]: Request rollback.
> 
> 2022-01-26 16:36:50,524 INFO JobMaster [pool-3-thread-1]: Vertex ExecutionVertex{id=1, name=4-[ReduceOperator -> SinkOperator]-0, resources={}, state=TO_ADD, containerId=ContainerId{id=f453da9a-b0a2-4366-8287-9d2ae5052f34}, workerActor=io.ray.runtime.actor.LocalModeActorHandle@6c0fd75d}, request job worker rollback cost 3ms, actorId=378c5378208707074fa846477c398dae.
> 
> 2022-01-26 16:36:50,525 INFO ResourceManagerImpl [pool-3-thread-1]: Current resource detail: Resources{registerContainers=[Container{id=ContainerId{id=cb86bc41-5a48-4302-b1a3-c2d74be243a9}, address=localhost1, hostname=localhost1, nodeId=31313131313131313131313131313131313131313131313131313131, availableResources={MEM=16.0, ContainerId{id=cb86bc41-5a48-4302-b1a3-c2d74be243a9}=500.0, CPU=1.0}, executionVertexIds=[0], capacity=1}, Container{id=ContainerId{id=f453da9a-b0a2-4366-8287-9d2ae5052f34}, address=localhost2, hostname=localhost2, nodeId=32323232323232323232323232323232323232323232323232323232, availableResources={MEM=16.0, ContainerId{id=f453da9a-b0a2-4366-8287-9d2ae5052f34}=500.0, CPU=2.0}, executionVertexIds=[1], capacity=1}, Container{id=ContainerId{id=b65ea6ba-331e-46e1-b5d6-3f6e4ef5f417}, address=localhost3, hostname=localhost3, nodeId=33333333333333333333333333333333333333333333333333333333, availableResources={MEM=16.0, ContainerId{id=b65ea6ba-331e-46e1-b5d6-3f6e4ef5f417}=500.0, CPU=3.0}, executionVertexIds=[], capacity=1}, Container{id=ContainerId{id=dd6ab2d6-2d02-437e-8d26-6a45f5946d3b}, address=localhost4, hostname=localhost4, nodeId=34343434343434343434343434343434343434343434343434343434, availableResources={MEM=16.0, CPU=4.0, ContainerId{id=dd6ab2d6-2d02-437e-8d26-6a45f5946d3b}=500.0}, executionVertexIds=[], capacity=1}, Container{id=ContainerId{id=0fb276b8-edd3-46b6-a270-618bc0be3994}, address=localhost5, hostname=localhost5, nodeId=35353535353535353535353535353535353535353535353535353535, availableResources={MEM=16.0, ContainerId{id=0fb276b8-edd3-46b6-a270-618bc0be3994}=500.0, CPU=5.0}, executionVertexIds=[], capacity=1}]}.
> 
> 2022-01-26 16:36:50,527 INFO FailoverCoordinator [pool-3-thread-1]: Request job worker rollback

Did you run test case in streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/demo/WordCountTest.java？

I mean memory channel can only be used in single process mode. This exception usually occurs while running in cluster mode with memory channel. 

You can upload full logs if all of configurations have been observed, then we could do some troubleshooting analysis based on it.

By the way, this test cases passed in my different environments.

**Comment by lpydhbt** [comment]
i  definitely  run test case in streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/demo/WordCountTest.java and 
 use memory channel in single process mode
full log:
[log1.txt](https://github.com/ray-project/mobius/files/7955243/log1.txt)
[log2.txt](https://github.com/ray-project/mobius/files/7955244/log2.txt)

**Comment by ashione** [comment]
> i  definitely  run test case in streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/demo/WordCountTest.java and 
> 
>  use memory channel in single process mode
> 
> full log:
> 
> [log1.txt](https://github.com/ray-project/mobius/files/7955243/log1.txt)
> 
> [log2.txt](https://github.com/ray-project/mobius/files/7955244/log2.txt)

Got it. I will check it latter today.

**Comment by ashione** [comment]
> i definitely run test case in streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/demo/WordCountTest.java and use memory channel in single process mode full log: [log1.txt](https://github.com/ray-project/mobius/files/7955243/log1.txt) [log2.txt](https://github.com/ray-project/mobius/files/7955244/log2.txt)

Pleas try this branch again https://github.com/ray-project/mobius/pull/16. I just noticed that methioned issue would be reproduced on mac os.

**Comment by lpydhbt** [comment]
> Got it. I will check it latter today.



> > i definitely run test case in streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/demo/WordCountTest.java and use memory channel in single process mode full log: [log1.txt](https://github.com/ray-project/mobius/files/7955243/log1.txt) [log2.txt](https://github.com/ray-project/mobius/files/7955244/log2.txt)
> 
> Pleas try this branch again #16. I just noticed that methioned issue would be reproduced on mac os.

tks,it works well。
