### ISSUE TITLE
[Docs] compile and setup instructions

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/mobius#53]
can we have document about how to compile and setup ray streaming? 

I am trying to do some mobius evaluation. I tried to do this manually, but I am not sure if I am doing it correctly. 

We may need to run mobius in the following environments.
* container
* linux environment.
* macosx environment

**Comment by ashione** [comment]
> can we have document about how to compile and setup ray streaming?
> 
> I am trying to do some mobius evaluation. I tried to do this manually, but I am not sure if I am doing it correctly.
> 
> We may need to run mobius in the following environments.
> 
> * container
> * linux environment.
> * macosx environment

Install instruction doc : https://github.com/ray-project/mobius/blob/master/docs/how-to-install.rst
The lastest mobius need some patches these cannot fetch from ray-1.12, so we need build ray manully([ray whl ](https://ray-mobius-us.oss-us-west-1.aliyuncs.com/ci/linux/ubuntu/b7d148815e427ccd47046d1c69ee3ab55bf7db3c/ray-2.0.0.dev0-cp38-cp38-linux_x86_64.whl)pakcage with python-3.8 on linux has been uploaded on aliyun oss bucket).

BTW, could you provide us more details about that requirements? Is only python or java used for evalution?

**Comment by BalaBalaYi** [comment]
We haven't done testing in a variety of environments, so there might be some problems. Please let us know if u have any problems for installing. 

BTW,  many implementations are outdated  by current. The repo will have huge changes in next few month.

**Comment by wilsonwang371** [comment]
I am planning to do some evaluation on the network communication overhead between Mobius and hazelcast. I did some deep-dive on Hazelcast and I am thinking comparing Mobius with it can help us get a better understanding of Ray core and where it needs to improve.

**Comment by BalaBalaYi** [comment]
> I am planning to do some evaluation on the network communication overhead between Mobius and hazelcast. I did some deep-dive on Hazelcast and I am thinking comparing Mobius with it can help us get a better understanding of Ray core and where it needs to improve.

@ashione I think we used to have performance test, is there any data we can provide to him?

**Comment by ashione** [comment]
> > I am planning to do some evaluation on the network communication overhead between Mobius and hazelcast. I did some deep-dive on Hazelcast and I am thinking comparing Mobius with it can help us get a better understanding of Ray core and where it needs to improve.
> 
> @ashione I think we used to have performance test, is there any data we can provide to him?

We do some perf test in two years ago(Mar, 2020), and get brief result :
WordCount 1X1 Job gets 450K TPS within 200bytes each word, Yahoobenchmark gets 1250K totally and 10ms lantency between upstream and downstream pair. cc @wilsonwang371

**Comment by wilsonwang371** [comment]
Thanks for the info. But in order to compare it with other alternatives, I need to setup a common setup for them. Let me do that and if I need you guys' help, I will open another issue to track this.
