### ISSUE TITLE
Is mobius suitable to be used in streaming data processing and model inference？

### ISSUE THREAD

**Issue by gtarcoder** [ray-project/mobius#59]
As title says, I am wondering if this repo is suitable to be used in streaming data processing and model inference? like data processing and inference in Flink

**Comment by gtarcoder** [comment]
> > As title says, I am wondering if this repo is suitable to be used in streaming data processing and model inference? like data processing and inference in Flink
> 
> Our work might help uesrs to build more close and united system that combines training platform and data processing pipeline based on ray AIR runtime.

What is its streaming pattern？ Is it more like spark or flink？

**Comment by ashione** [comment]
> > > As title says, I am wondering if this repo is suitable to be used in streaming data processing and model inference? like data processing and inference in Flink
> > 
> > 
> > Our work might help uesrs to build more close and united system that combines training platform and data processing pipeline based on ray AIR runtime.
> 
> What is its streaming pattern？ Is it more like spark or flink？

This doc https://docs.google.com/document/d/1niWddjvgdM0KJwM7vO2Ml4cxcwgKrQsR5a70ehF3K8k/edit might be useful to answer the above question.
In fact, we'd better support mainstream APIs contains DSL/DataStreamAPI(Dataflow api, flink and spark both take this, which is called data processing pattern lang) and SQL.

**Comment by gtarcoder** [comment]
> > > > As title says, I am wondering if this repo is suitable to be used in streaming data processing and model inference? like data processing and inference in Flink
> > > 
> > > 
> > > Our work might help uesrs to build more close and united system that combines training platform and data processing pipeline based on ray AIR runtime.
> > 
> > 
> > What is its streaming pattern？ Is it more like spark or flink？
> 
> This doc https://docs.google.com/document/d/1niWddjvgdM0KJwM7vO2Ml4cxcwgKrQsR5a70ehF3K8k/edit might be useful to answer the above question. In fact, we'd better support mainstream APIs contains DSL/DataStreamAPI(Dataflow api, flink and spark both take this, which is called data processing pattern lang) and SQL.

Get， So will this project be maintained continuely? It seems like it hasn't been updated for a long time

**Comment by ashione** [comment]
> > > > > As title says, I am wondering if this repo is suitable to be used in streaming data processing and model inference? like data processing and inference in Flink
> > > > 
> > > > 
> > > > Our work might help uesrs to build more close and united system that combines training platform and data processing pipeline based on ray AIR runtime.
> > > 
> > > 
> > > What is its streaming pattern？ Is it more like spark or flink？
> > 
> > 
> > This doc https://docs.google.com/document/d/1niWddjvgdM0KJwM7vO2Ml4cxcwgKrQsR5a70ehF3K8k/edit might be useful to answer the above question. In fact, we'd better support mainstream APIs contains DSL/DataStreamAPI(Dataflow api, flink and spark both take this, which is called data processing pattern lang) and SQL.
> 
> Get， So will this project be maintained continuely? It seems like it hasn't been updated for a long time

We need more contributors.
